import { createClient } from '@supabase/supabase-js';
const sb = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY);
const $=x=>document.getElementById(x); let rows=[], participants=[], testMode=false;
const average=a=>a.length?(a.reduce((s,x)=>s+x.tasks_completed,0)/a.length):0;
const fmt=n=>Number(n).toFixed(1);
function download(name, data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function csv(value){return '"'+String(value??'').replaceAll('"','""')+'"'}
async function authorize(){const {data:{session}}=await sb.auth.getSession();if(!session)return;const {data}=await sb.from('profiles').select('role').eq('id',session.user.id).single();if(data?.role!=='researcher'){await sb.auth.signOut();$('loginMsg').textContent='This account is not authorized for researcher access.';return} $('login').classList.add('hidden');$('dashboard').classList.remove('hidden');await loadTestMode();await load()}
async function load(){const [{data:p,error:pe},{data:d,error:de}]=await Promise.all([sb.from('participants').select('id,participant_code').order('participant_code'),sb.from('daily_productivity').select('*').order('date',{ascending:false})]);if(pe||de){alert('Could not load research data.');return}participants=p;rows=d;const sel=$('participantFilter');sel.innerHTML='<option value="">All participants</option>'+p.map(x=>`<option value="${x.id}">${x.participant_code}</option>`).join('');render()}
async function loadTestMode(){const {data,error}=await sb.from('study_settings').select('test_mode').eq('id',true).single();testMode=!error&&data?.test_mode===true;const button=$('reset');button.textContent='Reset Test Data';button.classList.toggle('hidden',!testMode);button.disabled=!testMode}
function resetDialog(){let dialog=$('resetTestModal');if(dialog)return dialog;dialog=document.createElement('dialog');dialog.id='resetTestModal';dialog.style.cssText='border:0;border-radius:21px;box-shadow:0 18px 55px #4a303066;max-width:400px;width:calc(100% - 32px);color:#4a3030;padding:24px;font-family:Nunito,sans-serif';dialog.innerHTML='<h2 style="font-family:Patrick Hand,cursive;font-size:30px;margin:0">⚠️ Reset Test Data?</h2><p style="color:#8b7070;font-weight:700;line-height:1.45">This will permanently delete participant TEST data from the research database. This cannot be undone.</p><div style="display:flex;justify-content:flex-end;gap:10px;margin-top:18px"><button class="btn outline" id="resetTestCancel">Cancel</button><button class="btn" style="background:#e87583" id="resetTestConfirm">Reset Test Data</button></div>';document.body.append(dialog);$('resetTestCancel').onclick=()=>dialog.close();$('resetTestConfirm').onclick=async()=>{const button=$('resetTestConfirm');button.disabled=true;const {error}=await sb.rpc('reset_test_data');if(error){alert(`Could not reset test data: ${error.message}`)}else{dialog.close();await loadTestMode();await load();alert('Test data successfully reset.')}button.disabled=false};return dialog}
function filtered(){return rows.filter(r=>(!$('participantFilter').value||r.participant_id===$('participantFilter').value)&&(!$('periodFilter').value||r.research_period===$('periodFilter').value)&&(!$('dateFilter').value||r.date===$('dateFilter').value))}
function render(){const all=filtered(), base=all.filter(x=>x.research_period==='BASELINE'),inter=all.filter(x=>x.research_period==='INTERVENTION'),ba=average(base),ia=average(inter), change=ia-ba;$('participants').textContent=participants.length;$('baselineAvg').textContent=fmt(ba);$('interventionAvg').textContent=fmt(ia);$('change').textContent=(change>=0?'+':'')+fmt(change);$('baselineBar').style.height=Math.max(26,ba*24)+'px';$('baselineBar').textContent=`${fmt(ba)} baseline`;$('interventionBar').style.height=Math.max(26,ia*24)+'px';$('interventionBar').textContent=`${fmt(ia)} StudyFlow`;
 const code=id=>participants.find(p=>p.id===id)?.participant_code||'—'; const tbody=$('daily');tbody.innerHTML=all.map(r=>`<tr><td>${code(r.participant_id)}</td><td>${r.date}</td><td>${r.research_period}</td><td>${r.tasks_created}</td><td>${r.tasks_completed}</td><td>${r.pomodoro_sessions}</td><td>${r.focused_minutes}</td></tr>`).join('')||'<tr><td colspan="7">No matching records.</td></tr>';
 const totals=Object.values(all.reduce((acc,r)=>{acc[r.date]=(acc[r.date]||0)+r.tasks_completed;return acc},{})).length; const dates=[...new Set(all.map(r=>r.date))].sort().slice(-10); const max=Math.max(1,...dates.map(d=>all.filter(r=>r.date===d).reduce((s,r)=>s+r.tasks_completed,0))); $('dailyChart').innerHTML=dates.map(d=>{const n=all.filter(r=>r.date===d).reduce((s,r)=>s+r.tasks_completed,0);return `<div class="bar ${n===max?'pink':''}" style="height:${Math.max(26,n/max*130)}px">${n}<br>${d.slice(5)}</div>`}).join('') || '<span class="sub">No matching daily records.</span>';
 $('comparison').innerHTML=participants.map(p=>{const pr=rows.filter(r=>r.participant_id===p.id),b=average(pr.filter(r=>r.research_period==='BASELINE')),i=average(pr.filter(r=>r.research_period==='INTERVENTION')),c=i-b;return `<tr><td>${p.participant_code}</td><td>${fmt(b)}</td><td>${fmt(i)}</td><td class="positive">${c>=0?'+':''}${fmt(c)}</td></tr>`}).join('');}
async function rawExport(){const [{data:tasks},{data:sessions}]=await Promise.all([sb.from('tasks').select('*'),sb.from('focus_sessions').select('*')]);const code=id=>participants.find(p=>p.id===id)?.participant_code||id;const visible=filtered();const allowed=new Set(visible.map(r=>`${r.participant_id}|${r.date}`));const allow=(id,stamp)=>allowed.has(`${id}|${String(stamp||'').slice(0,10)}`);const taskMap=new Map((tasks||[]).map(t=>[t.id,t]));const includedSessions=(sessions||[]).filter(s=>allow(s.participant_id,s.ended_at||s.started_at));const sessionTaskIds=new Set(includedSessions.map(s=>s.task_id).filter(Boolean));const includedTasks=(tasks||[]).filter(t=>allow(t.participant_id,t.created_at)||sessionTaskIds.has(t.id));let out='participant_id,task_id,task_title,subject,task_created_at,task_completed_at,task_completed,session_id,session_number,planned_duration,actual_duration,session_started_at,session_ended_at\n';const sessionsByTask=new Map();includedSessions.forEach(s=>sessionsByTask.set(s.task_id,[...(sessionsByTask.get(s.task_id)||[]),s]));includedTasks.forEach(t=>{const rows=sessionsByTask.get(t.id)||[{}];rows.forEach(s=>out+=[code(t.participant_id),t.id,t.title,t.subject,t.created_at,t.completed_at,t.completed,s.id,s.session_number,s.planned_duration,s.actual_duration,s.started_at,s.ended_at].map(csv).join(',')+'\n')});includedSessions.filter(s=>!s.task_id||!taskMap.has(s.task_id)).forEach(s=>out+=[code(s.participant_id),'','','','','','',s.id,s.session_number,s.planned_duration,s.actual_duration,s.started_at,s.ended_at].map(csv).join(',')+'\n');download('studyflow-raw-data.csv',out)}
function summaryExport(){let out='participant_id,date,research_period,tasks_created,tasks_completed,pomodoro_sessions_completed,focused_minutes\n';filtered().forEach(r=>out+=[participants.find(p=>p.id===r.participant_id)?.participant_code,r.date,r.research_period,r.tasks_created,r.tasks_completed,r.pomodoro_sessions,r.focused_minutes].map(csv).join(',')+'\n');download('studyflow-research-data.csv',out)}
$('loginBtn').onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){$('loginMsg').textContent='Sign-in failed. Check your credentials.';return}authorize()};$('signOut').onclick=()=>sb.auth.signOut().then(()=>location.reload());$('apply').onclick=render;$('summaryCsv').onclick=summaryExport;$('rawCsv').onclick=rawExport;$('reset').onclick=()=>{if(testMode)resetDialog().showModal()};authorize();
